export const modalProps = {
  onCloseHandler: () => {},
  actionModal: {
    isOpen: true,
    actionName: 'OPTIONS',
    title: 'Lựa Chọn Thuộc Tính',
    data: {
      product: {
        id: 189371737,
        master_id: 189371737,
        sku: '3345969485560',
        name: 'MacBook Air M2 2022',
        url_key: 'macbook-air-m2-2022-p189371737',
        url_path: 'macbook-air-m2-2022-p189371737.html?spid=189371739',
        short_url: 'https://tiki.vn/product-p189371737.html?spid=189371739',
        type: 'configurable',
        book_cover: null,
        short_description:
          'MacBook Air Chip M2Tiêu đềMacBook Air. Thiết kế mới. Chuẩn mực mới. MacBook Air. Không thể xem nhẹ. Nhẹ và nhanh. MacBook Air. Siêu mạnh mẽ với M2. Nhanh. Mỏng. Trong một.Nội dung quảng cáoSiêu mạ...',
        price: 28970000,
        list_price: 32990000,
        original_price: 32990000,
        badges: '[{…}]',
        badges_new: '[]',
        discount: 4020000,
        discount_rate: 12,
        rating_average: 5,
        review_count: 10,
        review_text: '(10)',
        favourite_count: 0,
        thumbnail_url:
          'https://salt.tikicdn.com/cache/280x280/ts/product/f4/f8/e3/78e3ee32a6ef35dc92a67d0f88a056fe.png',
        has_ebook: false,
        inventory_status: 'available',
        inventory_type: 'instock',
        productset_group_name:
          'Laptop - Máy Vi Tính - Linh kiện/Laptop/Macbook',
        is_fresh: false,
        seller: null,
        is_flower: false,
        has_buynow: true,
        is_gift_card: false,
        salable_type: null,
        data_version: 3300,
        day_ago_created: 113,
        all_time_quantity_sold: 47,
        meta_title: '',
        meta_description: '',
        meta_keywords: '',
        is_baby_milk: false,
        is_acoholic_drink: false,
        description:
          '<h2><strong>MacBook Air Chip M2</strong></h2>\n<h3>Tiêu đề</h3>\n<p>MacBook Air. Thiết kế mới. Chuẩn mực mới. <br />MacBook Air. Không thể xem nhẹ. <br />Nhẹ và nhanh. <br />MacBook Air. Siêu mạnh mẽ với M2. <br />Nhanh. Mỏng. Trong một.</p>\n<h3>Nội dung quảng cáo</h3>\n<p>Siêu mạnh mẽ với chip M2 thế hệ tiếp theo, MacBook Air được thiết kế mới, kết hợp giữa hiệu năng đáng kinh ngạc và thời lượng pin lên đến 18 giờ trong vỏ nhôm mỏng ấn tượng.<sup>1</sup></p>\n<h5>Tính năng nổi bật</h5>\n<ul>\n<li>Chi...',
        images: '[{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, …]',
        warranty_policy: null,
        brand: '{id: 17827, name: "Apple", slug: "apple"}',
        current_seller: '{id: 1, is_best_store: false, is_offline_installmen…}',
        other_sellers: '[]',
        seller_specifications: '[{…}, {…}]',
        specifications: '[{…}]',
        product_links: '[]',
        configurable_options: '[{…}, {…}]',
        configurable_products: '[{…}, {…}, {…}, {…}, {…}]',
        services_and_promotions: '[]',
        promitions: '[]',
        stock_item: '{max_sale_qty: 1000, min_sale_qty: 1, preorder_date…}',
        quantity_sold: '{text: "Đã bán 47", value: 47}',
        categories: '{id: 2458, is_leaf: true, name: "Macbook"}',
        breadcrumbs: '[{…}, {…}, {…}, {…}]',
        installment_info:
          '{month: 12, price: 2414166, redirect_url: "https://…}',
        installment_info_v2:
          '{details: null, redirect_url: "https://tiki.vn/inst…}',
        video_url:
          'https://sand.tikicdn.com/ts/video/a4/17/cb/8aa1c28ec2edd04527e9582477389422.mp4',
        is_seller_in_chat_whitelist: false,
        inventory: '{fulfillment_type: "tiki_delivery", product_virtual…}',
        warranty_info: '[{…}, {…}, {…}, {…}]',
        return_and_exchange_policy:
          'Đổi trả trong<br><b>7 ngày</b><br>nếu sp lỗi',
        asa_cashback_widget:
          '{amplitude: {…}, asa_plus_badge: "", astra_convert_…}',
        asa_share_btn: '{benefits: {…}, category_share: "Macbook (2458)", c…}',
        benefits: '[{…}, {…}, {…}]',
        productNotFound: false,
        badgesMap: '{new_pdp: {…}}',
      },
      selectedProduct: {
        child_id: 189371738,
        id: 189371739,
        images: '[{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, …]',
        inventory_status: 'available',
        name: 'Apple Macbook Air 2022 13.6 inch (Apple M2 - 8GB/ 256GB) - MLXW3SA/A - Space Gray',
        option1: 'Space Gray',
        option2: '8GB /256GB',
        price: 28970000,
        selected: true,
        seller: '{id: 1, name: "Tiki Trading"}',
        sku: '3534453562745',
        thumbnail_url:
          'https://salt.tikicdn.com/cache/280x280/ts/product/f4/f8/e3/78e3ee32a6ef35dc92a67d0f88a056fe.png',
      },
      selectedProductImages: [
        '{image: {…}, isVideo: true, photoForCustomer: false…}',
        '{image: {…}, photoForCustomer: false}',
        '{image: {…}, photoForCustomer: false}',
        '{image: {…}, photoForCustomer: false}',
        '{image: {…}, photoForCustomer: false}',
        '{image: {…}, photoForCustomer: false}',
        '{image: {…}, photoForCustomer: false}',
        '{image: {…}, photoForCustomer: false}',
        '{image: {…}, photoForCustomer: false}',
        '{image: {…}, photoForCustomer: false}',
        '{image: {…}, photoForCustomer: false}',
      ],
      isAddToCart: false,
      updateSelectConfigurable: 'ƒ updateSelectConfigurable() {}',
      onDone: () => {},
    },
    isImportModal: true,
  },
  dispatch: () => {},
};
